auth:
  audience: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
  custom-role-claim-key: https://carvis.cloud/roles
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://carvis.eu.auth0.com/
