auth:
  audience: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
  custom-role-claim-key: https://carvis.cloud/roles
  domain: https://carvis.eu.auth0.com/
  client-id: ${AUTH_CLIENT_ID}
  client-secret: ${AUTH_CLIENT_SECRET}

cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - DELETE

s3-buckets:
  bucket-names:
    images: carvis-dev-images

dynamodb:
  table-name-prefix: dev

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.domain}
  cache:
    cache-names: userNames,imageUrls,authorization
  caffeine:
    spec: maximumSize=500,expireAfterAccess=600s

logging:
  pattern:
    level: '[%X{traceId}]'

sentry:
  dsn: https://329f4264c94b452f8756d77a0c736606@o582664.ingest.sentry.io/6036448
  send-default-pii: true
  traces-sample-rate: 1.0
