cors:
  allowed-origins:
    - https://carvis.cloud

sentry:
  environment: live
  traces-sample-rate: 0.2
  sample-rate: 1.0

dynamodb:
  table-name-prefix: live

s3-buckets:
  bucket-names:
    images: carvis-live-images
