auth:
  audiences:
    user: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
    system: https://system.carvis.cloud
  custom-role-claim-key: https://carvis.cloud/roles
  domain: https://carvis.eu.auth0.com/
  client-id: ${AUTH_CLIENT_ID}
  client-secret: ${AUTH_CLIENT_SECRET}

cors:
  allowed-origins:
    - https://dev.carvis.cloud
    - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - DELETE

s3:
  prefix: carvis-dev
  buckets:
    images: ${s3.prefix}-images

dynamodb:
  table-name-prefix: dev

sqs:
  prefix: carvis-dev
  queues:
    user-signup: ${sqs.prefix}-user_signup
    carvis-command: ${sqs.prefix}-carvis_command
    carvis-event: ${sqs.prefix}-carvis_event

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.domain}
  cache:
    cache-names:
      - auth0-users
      - image-urls
      - cars-authorization
      - requests-authorization
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

logging:
  cloud.carvis: debug

  application:
    name: carvis-api

sentry:
  dsn: https://329f4264c94b452f8756d77a0c736606@o582664.ingest.sentry.io/6036448
  send-default-pii: true
  traces-sample-rate: 1.0
  sample-rate: 1.0
  environment: dev
  logging:
    minimum-event-level: warn

aws:
  region: eu-west-1

cloud:
  aws:
    sns:
      enabled: false
    region:
      static: ${aws.region}

email:
  enabled: true
  user-signup:
    from-mail: usersignup@carvis.cloud
    user-management-url: https://carvis.cloud/user-management

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
