auth:
  audience: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
  custom-role-claim-key: https://carvis.cloud/roles

cors:
  allowed-origins:
    - https://carvis.cloud
  allowed-methods:
    - GET
    - OPTIONS

s3-buckets:
  bucket-names:
    images: carvis-dev-images

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://carvis.eu.auth0.com/
