cors:
  allowed-origins:
    - https://carvis.cloud

sentry:
  environment: live
  sample-rate: 0.2

dynamodb:
  table-name-prefix: live

s3:
  buckets:
    images: carvis-live-images

sqs:
  queues:
    prefix: carvis-live
