auth:
  audience: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
  custom-role-claim-key: https://carvis.cloud/roles
  domain: https://carvis.eu.auth0.com/
  client-id: ${AUTH_CLIENT_ID}
  client-secret: ${AUTH_CLIENT_SECRET}

cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - DELETE

s3:
  buckets:
    images: carvis-dev-images

dynamodb:
  table-name-prefix: dev

sqs:
  queues:
    user-signup: carvis-dev-user_signup
    carvis-command: carvis-dev-carvis_command

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.domain}
  cache:
    cache-names:
      - auth0-users
      - imageUrls
      - carsAuthorization
      - requestsAuthorization
      - usersAuthorization
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

logging:
  cloud.carvis: debug

  application:
    name: carvis-api

sentry:
  dsn: https://329f4264c94b452f8756d77a0c736606@o582664.ingest.sentry.io/6036448
  send-default-pii: true
  traces-sample-rate: 1.0

aws:
  region: eu-west-1

cloud:
  aws:
    sns:
      enabled: false
    region:
      static: ${aws.region}

email:
  enabled: true
  user-signup:
    from-mail: usersignup@carvis.cloud
    user-management-url: https://carvis.cloud/user-management

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
