auth:
  audience: ukQnXHJoRrZwGf85Uh4Jpk8V932GsfKt
  custom-role-claim-key: https://carvis.cloud/roles

cors:
  allowed-origins:
    - https://carvis.cloud
  allowed-methods:
    - GET
    - OPTIONS

s3-buckets:
  bucket-names:
    images: carvis-dev-images

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://carvis.eu.auth0.com/

sentry:
  dsn: https://329f4264c94b452f8756d77a0c736606@o582664.ingest.sentry.io/6036448
  send-default-pii: true
  environment: local