package cloud.carvis.api.model.entities

import cloud.carvis.api.dao.converters.DynamoDbInstantConverter
import com.amazonaws.services.dynamodbv2.datamodeling.*
import org.springframework.data.annotation.CreatedBy
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedBy
import org.springframework.data.annotation.LastModifiedDate
import java.time.Instant
import java.util.*

@DynamoDBTable(tableName = "carvis-requests")
data class RequestEntity(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    override var id: UUID? = null,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDbInstantConverter::class)
    @CreatedDate
    override var createdAt: Instant? = null,

    @DynamoDBAttribute
    @CreatedBy
    override var createdBy: String? = null,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDbInstantConverter::class)
    @LastModifiedDate
    override var updatedAt: Instant? = null,

    @DynamoDBAttribute
    @LastModifiedBy
    override var updatedBy: String? = null,

    ) : Entity()
