package cloud.carvis.api.model.entities

import cloud.carvis.api.dao.converters.DynamoDbInstantConverter
import com.amazonaws.services.dynamodbv2.datamodeling.*
import org.springframework.data.annotation.CreatedBy
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedBy
import org.springframework.data.annotation.LastModifiedDate
import java.time.Instant
import java.util.*

@DynamoDBTable(tableName = "carvis-requests")
data class RequestEntity(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    override var id: UUID? = null,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDbInstantConverter::class)
    @CreatedDate
    override var createdAt: Instant? = null,

    @DynamoDBAttribute
    @CreatedBy
    override var createdBy: String? = null,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDbInstantConverter::class)
    @LastModifiedDate
    override var updatedAt: Instant? = null,

    @DynamoDBAttribute
    @LastModifiedBy
    override var updatedBy: String? = null,

    @DynamoDBAttribute
    var additionalEquipment: String? = null,

    @DynamoDBAttribute
    var bodyType: String? = null,

    @DynamoDBAttribute
    var brand: String? = null,

    @DynamoDBAttribute
    var budget: String? = null,

    @DynamoDBAttribute
    var capacity: Long? = null,

    @DynamoDBAttribute
    var countryOfOrigin: String? = null,

    @DynamoDBAttribute
    var colorExterior: String? = null,

    @DynamoDBAttribute
    var colorExteriorManufacturer: String? = null,

    @DynamoDBAttribute
    var colorAndMaterialInterior: String? = null,

    @DynamoDBAttribute
    var condition: String? = null,

    @DynamoDBAttribute
    var contactName: String? = null,

    @DynamoDBAttribute
    var contactCompany: String? = null,

    @DynamoDBAttribute
    var contactFreeText: String? = null,

    @DynamoDBAttribute
    var contactPhone: String? = null,

    @DynamoDBAttribute
    var contactEmail: String? = null,

    @DynamoDBAttribute
    var description: String? = null,

    @DynamoDBAttribute
    var highlights: String? = null,

    @DynamoDBAttribute
    var horsePower: Long? = null,

    @DynamoDBAttribute
    var mileage: Long? = null,

    @DynamoDBAttribute
    var mustHaves: String? = null,

    @DynamoDBAttribute
    var noGos: String? = null,

    @DynamoDBAttribute
    var ownerName: String? = null,

    @DynamoDBAttribute
    var modelDetails: String? = null,

    @DynamoDBAttribute
    var modelSeries: String? = null,

    @DynamoDBAttribute
    var modelYear: String? = null,

    @DynamoDBAttribute
    var transmission: String? = null,

    @DynamoDBAttribute
    var type: String? = null,

    @DynamoDBAttribute
    var vision: String? = null

    ) : Entity()
