name: build

on: [push, pull_request]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      branch_w_sha: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Declare build variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's#/#-#g')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Compile
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew compileKotlin

      - name: Build
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew -PcliVersion=${{ needs.prepare.outputs.branch_w_sha }} build -x test

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ needs.prepare.outputs.branch_w_sha }}
          path: build/libs

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew test --info
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
      - test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ needs.prepare.outputs.branch_w_sha }}
          path: build/libs

      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: carvis
          environment_name: carvis-live
          version_label: ${{ needs.prepare.outputs.branch_w_sha }}
          region: eu-west-1
          deployment_package: build/libs/carvis-api-${{ needs.prepare.outputs.branch_w_sha }}.jar
          use_existing_version_if_available: true
          wait_for_environment_recovery: 300

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - prepare
      - deploy
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: carvis
          SENTRY_PROJECT: api
        with:
          environment: ${{ needs.prepare.outputs.branch }}
