name: build

on: [push, pull_request]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      branch_w_sha: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Declare build variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's#/#-#g')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Compile
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew compileKotlin

      - name: Build
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew -PcliVersion=${{ needs.prepare.outputs.branch_w_sha }} build -x test

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ needs.prepare.outputs.branch_w_sha }}
          path: build/libs

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew test --info
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml
