name: "Docker"
on: [push, pull_request]

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 547284448024.dkr.ecr.eu-west-1.amazonaws.com

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.vars.outputs.branch }}
      branch_w_sha: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Declare build variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    name: Create and Push Docker Image
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Compile
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew compileKotlin

      - name: Test
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew test --info

      - name: Build
        shell: bash
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: carvis
          environment_name: carvis-${{ needs.prepare.outputs.branch }}
          version_label: ${{ needs.prepare.outputs.branch_w_sha }}
          region: eu-west-1
          deployment_package: build/libs/backend-0.0.1-SNAPSHOT.jar  # TODO
          use_existing_version_if_available: true
          wait_for_environment_recovery: 300
